include: lib/lints.yaml

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules-exclude:
    - prefer-publish-to-none: true
  rules-exclude:
    - prefer-publish-to-none: true
