name: netglade_analysis
version: 1.1.2
description: Lint rules for Dart and Flutter used internally at netglade.
repository: https://github.com/netglade/netglade_analysis
issue_tracker: https://github.com/netglade/netglade_analysis/issues
homepage: https://github.com/netglade/netglade_analysis
documentation: https://github.com/netglade/netglade_analysis

environment:
  sdk: ">=2.18.0 <3.0.0"
