name: netglade_analysis
version: 1.1.0
description: Lint rules for Dart and Flutter used internally at NetGlade.
repository: https://github.com/NetGlade/netglade_analysis
issue_tracker: https://github.com/NetGlade/netglade_analysis/issues
homepage: https://github.com/NetGlade/netglade_analysis
documentation: https://github.com/NetGlade/netglade_analysis

environment:
  sdk: ">=2.18.0 <3.0.0"
