include: package:netglade_analysis/lints.yaml

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  rules:
    avoid-duplicate-collection-elements:
      exclude:
        - test/**
  pubspec-rules:
    prefer-publish-to-none: false
