name: netglade_flutter_utils_example
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  netglade_analysis: ^8.0.0
  netglade_flutter_utils:
    path: ..

flutter:
  uses-material-design: true
