name: netglade_utils test

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'netglade_utils-v*'
    paths:
      - 'packages/netglade_utils/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/netglade_utils/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: packages/netglade_utils

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --line-length 120 --set-exit-if-changed .

      - name: Flutter Analyze
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        uses: CQLabs/dcm-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ci_key: ${{ secrets.DCM_KEY }}
          email: ${{ secrets.DCM_EMAIL }}
          folders: .
          fatal_style: true
          fatal_performance: true
          fatal_warnings: true

      - name: Dry Publish
        run: flutter pub publish --dry-run || true
